esphome:
  name: "${name}"
  friendly_name: "${NAME}"
  libraries:
    - rtl_433_ESP=https://github.com/NorthernMan54/rtl_433_ESP.git#v0.3.2
    - RadioLib@6.1.0
  includes:
    - 433/rtl433-to-mqtt.h
  platformio_options:
    lib_ldf_mode: "chain+"
    build_flags:
      - '-DONBOARD_LED=2'
      - '-DRF_MODULE_FREQUENCY=433.92'
      - '-DRF_MODULE_INIT_STATUS=true'    # Display transceiver config during startup
      # *** rtl_433_ESP Options ***
      #- '-DRTL_DEBUG=4'             # rtl_433 verbose mode
      #- '-DRTL_VERBOSE=58'          # LaCrosse TX141-Bv2, TX141TH-Bv2, TX141-Bv3, TX141W, TX145wsdth sensor
      #- '-DRAW_SIGNAL_DEBUG=true'   # display raw received messages
      #- '-DMEMORY_DEBUG=true'       # display memory usage information
      - '-DDEMOD_DEBUG=true'         # display signal debug info
      #- '-DMY_DEVICES=true'         # subset of devices
      - '-DPUBLISH_UNPARSED=true'    # publish unparsed signal details
      #- '-DRSSI_THRESHOLD=12'       # Apply a delta of 12 to average RSSI level
      #- '-DAVERAGE_RSSI=5000'       # Display RSSI floor ( Average of 5000 samples )
      - '-DSIGNAL_RSSI=true'         # Display during signal receive
      - '-DNO_DEAF_WORKAROUND=true'
      # *** RF Module Options ***
      - '-DRF_CC1101="CC1101"'       # CC1101 Transceiver Module
      #- '-DRF_MODULE_CS=5'          # pin to be used as chip select
      - '-DRF_MODULE_GDO0=12'        # CC1101 pin GDO0
      - '-DRF_MODULE_GDO2=27'        # CC1101 pin GDO2
      # *** RadioLib Options ***
      #- '-DRADIOLIB_DEBUG=true'
      #- '-DRADIOLIB_VERBOSE=true'
      
esp32:
  board: mhetesp32minikit
  framework:
    type: arduino

custom_component:
  - id: rtl433
    lambda: return { new Rtl433ToMqtt("${name}") };

interval:
  - interval: 60s
    then:
      - lambda: Rtl433ToMqtt::get(rtl433)->status();
