esphome:
  name: "rtl433"
  friendly_name: "RTL433 MQTT Gateway"
  comment: "LILYGO LoRa32 (ttgo-lora32-v21)"
  libraries:
    - rtl_433_ESP=https://github.com/mag1024/rtl_433_ESP.git#esp-idf
    - RadioLib@6.2.0
  platformio_options:
    lib_ldf_mode: "chain+"
    build_flags:
      - '-DONBOARD_LED=25'
      - '-DMY_DEVICES'
      - '-DRF_MODULE_CS=18'
      - '-DRF_MODULE_SCK=5'
      - '-DRF_MODULE_RST=23'
      - '-DRF_MODULE_DIO0=26'
      - '-DRF_MODULE_DIO1=33'
      - '-DRF_MODULE_DIO2=32'
      - '-DRF_SX1278'
      - '-DRF_MODULE_FREQUENCY=433.92'
      # - '-DLOG_LEVEL=LOG_VERBOSE'
      # - '-DPUBLISH_UNPARSED=true'
      # - '-DRTL_VERBOSE=63'
      # - '-DRTL_DEBUG=2'
      # - '-DRAW_SIGNAL_DEBUG'

esp32:
  board: ttgo-lora32-v21
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y

external_components:
  - source: github://mag1024/esphome-rtl433

rtl433_mqtt:
  id: gateway
  mqtt_id: my_mqtt

ota:
  on_begin:
    - rtl433_mqtt.stop: gateway
