# I use the espidf verison, so this may be somewhat out-of-date.

esphome:
  name: "rtl433"
  friendly_name: "RTL433 MQTT Gateway"
  comment: "LILYGO LoRa32 (ttgo-lora32-v21)"
    - rtl_433_ESP=https://github.com/NorthernMan54/rtl_433_ESP.git
    - RadioLib@6.2.0
  platformio_options:
    lib_ldf_mode: "chain+"
    build_flags:
      - '-DONBOARD_LED=LED_BUILTIN'
      - '-DRF_SX1278'
      - '-DRF_MODULE_FREQUENCY=433.92'
      # - '-DLOG_LEVEL=LOG_VERBOSE'
      # - '-DPUBLISH_UNPARSED=true'
      # - '-DRTL_VERBOSE=63'
      # - '-DRTL_DEBUG=2'
      # - '-DRAW_SIGNAL_DEBUG'

esp32:
  board: ttgo-lora32-v21
  framework:
    type: arduino

mqtt:
  ...
  id: my_mqtt

external_components:
  - source: github://mag1024/esphome-rtl433

rtl433_mqtt:
  id: gateway
  mqtt_id: my_mqtt

ota:
  on_begin:
    - rtl433_mqtt.stop: gateway
